#
# ~/.config/bottom/bottom.toml
#
# See https://github.com/ClementTsang/bottom/blob/master/sample_configs/default_config.toml.
#

[flags]
# Whether to hide the average cpu entry
hide_avg_cpu=true
# Shows an indicator in table widgets tracking where in the list you are
show_table_scroll_position=true

# Built-in themes
color = "gruvbox"

# Override default layout
[[row]]
    ratio=1
    [[row.child]]
        ratio=4
        type="cpu"
    [[row.child]]
        ratio=3
        type="mem"
    [[row.child]]
        ratio=3
        type="net"
[[row]]
    ratio=2
    [[row.child]]
        type="proc"
        default=true
