#
# ~/.SpaceVim.d/init.toml
#
# See https://spacevim.org/documentation.
#

# All SpaceVim option below [option] section
[options]

    # Disable SpaceVim automatic update at startup
    # Update will be down by pulling ~/.SpaceVim repository manually
    automatic_update = false

    # Colorschemes

    # Set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme layer
    colorscheme = "onedark"
    colorscheme_bg = "dark"

    # Disable guicolors in basic mode, many terminal do not support 24bit true colors
    enable_guicolors = false

    # Statusline

    # Disable statusline separator, if you want to use other value, please install nerd fonts
    statusline_separator = "nil"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = true
    statusline_unicode = true

    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true

    # Relative numbering
    relativenumber = false

    # Code indentation
    default_indent = 4
    expand_tab = true

# Autocomplete layer
[[layers]]
    name = 'autocomplete'
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "cycle"

# Colorscheme layer
[[layers]]
    name = 'colorscheme'

# Core layer
[[layers]]
    name = 'core'
    filetree_show_hidden = true

# Git
[[layers]]
    name = 'git'

# Shell layer
[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

# Version control
[[layers]]
    name = 'VersionControl'

