#
# ~/.config/topgrade.toml
#
# See https://github.com/topgrade-rs/topgrade/blob/master/config.example.toml.
#

# Run specific steps - same options as the command line flag
only = [
   "brew_cask",
   "brew_formula",
   "custom_commands",
   "gem",
   "git_repos",
   "mas",
   "pip3",
   "shell",
   "system",
   "yadm"
]

# Skip the preamble displayed when topgrade is run
display_preamble = false

# Custom commands
[commands]
"Brew cleanup" = "brew cleanup"

# Git repositories
[git]
repos = [
    "~/.SpaceVim",
]
